# Generated by Django 2.1.1 on 2018-09-13 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingresa el nombre de la categoría', max_length=200)),
                ('description', models.CharField(help_text='Ingresa la descripción de la categoría', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el producto', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Ingresa una breve descripción del producto', max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('a', 'Activo'), ('i', 'Inactivo')], default='a', help_text='Disponibilidad del producto', max_length=1)),
                ('category', models.ForeignKey(help_text='Selecciona una categoría para este producto', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(help_text='Selecciona la unidad de medida del producto', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Unit'),
        ),
    ]
